apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-container
          image: lodenn/auth-api:c5ce059639ca16063bedf05b9929f3b154dc0879
          env:
            - name: TOKEN_KEY
              value: secrettoken!
      restartPolicy: Always
