apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-container
          image: lodenn/auth-api:e1e0b8a7ac70fac0492c8f1eec9b93fd793ca4d9
          env:
            - name: TOKEN_KEY
              value: secrettoken!
      restartPolicy: Always
