apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-container
          image: lodenn/auth-api:5a6e2fe342ab3a564a961ca8c06b53493b2e148a
          env:
            - name: TOKEN_KEY
              value: secrettoken!
