apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
        - name: users-container
          image: lodenn/users-api:f8bcbd4c7e208e41175b64ed4552b76b53f6aee6
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: MONGO_INITDB_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: MONGO_DB_HOST
            - name: AUTH_API_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: AUTH_API_ADDRESS
      restartPolicy: Always
