apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
        - name: users-container
          image: lodenn/users-api:f8bcbd4c7e208e41175b64ed4552b76b53f6aee6
          env:
            - name: TOKEN_KEY
              value: secrettoken
            - name: MONGO_INITDB_DATABASE
              value: users
            - name: MONGO_INITDB_ROOT_USERNAME
              value: Admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: DIf4CMoPGnz49cCi
            - name: MONGO_DB_HOST
              value: cluster0.4ilq27g.mongodb.net
            - name: AUTH_API_ADDRESS
              value: auth-service.smartauthns:3000
      restartPolicy: Always
