apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
        - name: users-container
          image: lodenn/users-api:19fa28f5d0f130ec0259d838a685133581840d18
          env:
            - name: TOKEN_KEY
              value: secrettoken!
            - name: MONGO_INITDB_DATABASE
              value: users
            - name: MONGO_INITDB_ROOT_USERNAME
              value: Admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mJPdD57enYZm4aRl
            - name: MONGO_DB_HOST
              value: cluster0.bzovdv3.mongodb.net
            - name: AUTH_API_ADDRESS
              value: auth-service.smartauthns:3000
      restartPolicy: Always
