apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
        - name: users-container
          image: lodenn/users-api:fbe6fcc73cfba67a1f554298c5bbf8ef36dba3e5
          env:
            - name: TOKEN_KEY
              value: secrettoken!
            - name: MONGO_INITDB_DATABASE
              value: users
            - name: MONGO_INITDB_ROOT_USERNAME
              value: Admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: v4fFNKRLNF9TN5mL
            - name: MONGO_DB_HOST
              value: cluster0.bzovdv3.mongodb.net
            - name: AUTH_API_ADDRESS
              value: auth:3000
      restartPolicy: Always
