apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-storage-claimer
spec:
  volumeName: users-storage
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
